"""two table

Revision ID: 754917327869
Revises: 05dc333dd7a0
Create Date: 2026-05-12 20:24:54.139390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754917327869'
down_revision = '05dc333dd7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(length=255), nullable=False),
    sa.Column('valor_mensal', sa.Float(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], name='fk_assinatura_loja'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assinatura_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('invoice_slug', sa.String(length=100), nullable=True),
    sa.Column('order_nsu', sa.String(length=100), nullable=True),
    sa.Column('transaction_nsu', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.Column('capture_method', sa.String(length=50), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payment_url', sa.String(length=500), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], name='fk_pagamento_assinatura'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_slug'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento')
    op.drop_table('assinaturas')
    # ### end Alembic commands ###
