"""Adiciona tabela desp

Revision ID: c1f9c7ac8c6a
Revises: 754917327869
Create Date: 2026-06-20 09:00:11.190795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f9c7ac8c6a'
down_revision = '754917327869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas_simples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('despesas_simples')
    # ### end Alembic commands ###
